# Merge V1-V41 migrations into single V1__baseline.sql
# Combines schema_dump (DDL) + data_dump (INSERT) cleanly

$schemaFile = Join-Path $env:TEMP 'schema_dump.sql'
$dataFile   = Join-Path $env:TEMP 'data_dump.sql'
$outFile    = 'D:\develop\auto-test-platform\backend\platform-server\src\main\resources\db\migration\V1__baseline.sql'

$schemaText = [System.IO.File]::ReadAllText($schemaFile)
$dataText   = [System.IO.File]::ReadAllText($dataFile)

# Markers: mysqldump trailing restore block and INSERT start
$restoreMarker = '/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE'
$insertMarker  = '/*!40000 ALTER TABLE'

# Schema: split at restore block -> body(SET+CREATE) + restore
$si = $schemaText.IndexOf($restoreMarker)
$schemaBody    = $schemaText.Substring(0, $si)
$schemaRestore = $schemaText.Substring($si)

# Data: extract INSERT section only (skip SET block and restore block)
$di = $dataText.IndexOf($insertMarker)
$dr = $dataText.IndexOf($restoreMarker)
$dataInserts = $dataText.Substring($di, $dr - $di).TrimEnd()

# Header comment (English to avoid encoding issues in .ps1)
$nl = [char]13 + [char]10
$headerLines = @(
    '-- ============================================================',
    '-- V1 baseline: merged V1-V41 final schema and initial data',
    '--',
    '-- Generated by mysqldump from a database with all V1-V41 applied.',
    '-- Contains full table structure (DDL) and system initial data',
    '-- (roles, permissions, menus, dictionaries, global settings).',
    '-- admin user is created by DataInitializer at startup, not included.',
    '-- flyway_schema_history is managed by Flyway framework, not included.',
    '-- ============================================================',
    ''
)
$header = $headerLines -join $nl

# Combine: header + schemaBody + INSERTs + restore
$combined = $header + $schemaBody + $nl + $dataInserts + $nl + $nl + $schemaRestore

# Write as UTF-8 without BOM
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outFile, $combined, $utf8NoBom)

Write-Host "V1__baseline.sql created"
Write-Host "Size: $((Get-Item $outFile).Length) bytes"
Write-Host "Lines: $((Get-Content $outFile).Count)"
